### ISSUE TITLE
Error after running the stub

### ISSUE THREAD

**Issue by PeakScripts** [Blank-c/Blank-Grabber#126]
Sometimes this error appear after i run the exe but sometimes they dont how do i fix it
![image](https://user-images.githubusercontent.com/122708389/218605342-5929de3b-fe40-433c-b080-0a2a1f639b0c.png)
Traceback (most recent call last):
  File "<string>", line 2320, in <module>
  File "<string>", line 1502, in __init__
  File "<string>", line 1524, in cleanUp
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Dell\\AppData\\Local\\Temp\\Blank-Dell.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main-o.py", line 5, in <module>
  File "<string>", line 2, in <module>
  File "<string>", line 2330, in <module>
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Dell\\AppData\\Local\\Temp'

**Comment by Blank-c** [comment]
It looks like your antivirus is interfering with the grabber. You should turn it off and then try again.

**Comment by Blank-c** [comment]
I have added a handler to that, you may try the updated version now
