### ISSUE TITLE
i see this error when i run the .exe

### ISSUE THREAD

**Issue by Sajjad-1337** [Blank-c/Blank-Grabber#144]
Traceback (most recent call last):
  File "main-o.py", line 5, in <module>
  File "<string>", line 2, in <module>
  File "<string>", line 580, in <module>
  File "<string>", line 668, in Browsers
TypeError: 'type' object is not subscriptable

**Comment by Sajjad-1337** [comment]
![Screenshot_75](https://user-images.githubusercontent.com/44970279/223178636-66e5a269-d7a9-4459-83fb-ca99dad5b1dc.png)

**Comment by Blank-c** [comment]
Windows 7 is not supported.

**Comment by Blank-c** [comment]
You have something else to say?
