### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by darqeeq** [Blank-c/Blank-Grabber#150]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\darqe\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\Scripts\pyinstaller.exe\__main__.py", line 4, in <module>
  File "c:\users\darqe\downloads\blank-grabber-main (1)\blank-grabber-main\blank grabber\env\lib\site-packages\PyInstaller\__init__.py", line 17, in <module>
    from PyInstaller import compat
  File "c:\users\darqe\downloads\blank-grabber-main (1)\blank-grabber-main\blank grabber\env\lib\site-packages\PyInstaller\compat.py", line 165, in <module>
    is_ms_app_store = is_win and os.path.getsize(python_executable) == 0
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
OSError: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\darqe\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\python.exe'
Building failed!
Press any key to continue . . .

**Comment by darqeeq** [comment]
when trying to build

**Comment by Blank-c** [comment]
Please check #152 and see if it works for you.
