### ISSUE TITLE
my webhook is not working when i press test webhook in the gui and also nothing happening when i click the trojan exe in my second pc 

### ISSUE THREAD

**Issue by darknightmc80** [Blank-c/Blank-Grabber#215]
![image](https://github.com/Blank-c/Blank-Grabber/assets/135541360/7ffbada6-baa1-4426-b1b8-891888ec7a21)
i used a diffrent new one but still not working

**Comment by Blank-c** [comment]
What webhook did you type? Can you write the exact same webhook here.

**Comment by darknightmc80** [comment]
here

> What webhook did you type? Can you write the exact same webhook here.

here ; https://discord.com/api/webhooks/1117464328099069952/7fg_8bV5Ti9CTkiAnUCIN1zm8rNa1pOZMyEZkewnu7U5YwTar4KPt3muSDGi0_xnlo9J

**Comment by Blank-c** [comment]
Are you sure you have internet connection in the PC you are checking it?

**Comment by darknightmc80** [comment]
> Are you sure you have internet connection in the PC you are checking it?

100% case i just sent the file to it via a file sharing website so yea it has internet

**Comment by darknightmc80** [comment]
um its saying my webhook is working did you use it ?


> Are you sure you have internet connection in the PC you are checking it?

**Comment by Blank-c** [comment]
Can you type this command in cmd `python -c "from urllib.request import urlopen, Request;import json;print(urlopen(Request(url= 'https://discord.com/api/webhooks/1117464328099069952/7fg_8bV5Ti9CTkiAnUCIN1zm8rNa1pOZMyEZkewnu7U5YwTar4KPt3muSDGi0_xnlo9J', method= 'POST', data = json.dumps({'content' : 'your webhook is working'}).encode(), headers= {'Content-Type' : 'application/json', 'user-agent' : 'Mozilla/5.0 (Linux; Android 10; SM-T510 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.159 Safari/537.36'})).status==204)"`

**Comment by darknightmc80** [comment]
this Traceback (most recent call last):
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1458, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\darkn\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by Blank-c** [comment]
I think I know the cause of this error. Can you visit the webhook link with your browse?

**Comment by Blank-c** [comment]
It looks like your firewall is blocking the connection. Try using a VPN (and turning off antivirus) and see if the error arises again using the same command I gave you.

**Comment by darknightmc80** [comment]
> It looks like your firewall is blocking the connection. Try using a VPN (and turning off antivirus) and see if the error arises again using the same command I gave you.

ok and my firewall was off from the beginning ill try the vpn

**Comment by darknightmc80** [comment]
> 

it says its true in the cmd and working in the gui thanks

**Comment by Blank-c** [comment]
> > 
> 
> it says its true in the cmd and working in the gui thanks

VPN fixed it?

**Comment by darknightmc80** [comment]
> > > 
> > 
> > 
> > it says its true in the cmd and working in the gui thanks
> 
> VPN fixed it?

yep
